### ISSUE TITLE
Add current control sets

### ISSUE THREAD

**Issue by cugu** [forensicanalysis/artifacts#35]
Define and use control sets in other artifacts.

Idea:
```
name: WindowsRegistryCurrentControlSets
doc: The control sets of the Windows Registry.
sources:
- type: REGISTRY_KEY
  attributes:
    keys: 
      - 'HKEY_LOCAL_MACHINE\System\ControlSet*'
      - 'HKEY_LOCAL_MACHINE\System\CurrentControlSet'
  provides:
    - key: control_sets
supported_os: [Windows]
```
